### ISSUE TITLE
No googletest distribution in download (from a new user/evaluator)

### ISSUE THREAD

**Issue by wcmcspad** [amiq-consulting/fc4sc#1]
In the "FC4SC User's Guide" (page 12),  it  says that a googletest distribution comes with the package.  I find no "test/googletest" directory as specified in the manual.

Is the manual wrong?
If not,  where do I find the googletest distribution?

Bill McSpadden

**Comment by amiq-consulting** [comment]
Hi McSpadden,

Yes, you are correct, the manual is outdated; we have decided to not include the googletest distribution as it can be easily downloaded from the github. We recommend version 1.8.0, because it was tested to work with FC4SC:
$> wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
From here you can just extract the archive and move it inside the fc4sc/test directory and then follow the steps in the user guide in order to compile it.

Best Regards

**Comment by amiq-consulting** [comment]
Hi,

The User guide has been updated with correct information in the following commit: [https://github.com/amiq-consulting/fc4sc/commit/d13df09eabfe05f295e5109ab9e5fa614cd6244e](https://github.com/amiq-consulting/fc4sc/commit/d13df09eabfe05f295e5109ab9e5fa614cd6244e)
This version also includes a script for automatically downloading the googletest distribution in order to ease the process. For more information, check the user guide.

Best Regards
