### ISSUE TITLE
Coverage GUI: Illegal Bins reduce total coverage percentage of the coverpoints and instances

### ISSUE THREAD

**Issue by karrenb** [amiq-consulting/fc4sc#17]
I created an illegal bin, to throw an exception when reaching an illegal state in a state machine. In the simulation this works fine and i will get 100% coverage, but when I look at the coverage report in the HTML GUI, it will not add up to 100% because the illegal bin has no hit count. This seems not to be a correct behavior.

**Comment by amiq-consulting** [comment]
Hello karrenb,

You are correct, the behavior for illegal_bins was backwards in the GUI. Now illegal_bins with 0 hits will be displayed in light green and won't drop the percentage anymore. The ones with hits will be red and lower your percentage.
Fixed in the latest commit.
Thanks for reporting this!
